---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: tautulli
    state: absent

- name: Wait for Plex Logs folder to be created by Plex
  wait_for:
    path: "/opt/plex/Library/Application Support/Plex Media Server/Logs"
    state: present

- name: Create tautulli directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/tautulli

- name: Create and start container
  docker_container:
    name: tautulli
    image: shiggins8/tautulli
    pull: yes
    published_ports:
      - "127.0.0.1:8182:8181"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "tautulli.{{domain}}"
      VIRTUAL_PORT: 8181
      LETSENCRYPT_HOST: "tautulli.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/tautulli:/config"
      - "/opt/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    restart_policy: always
    networks:
      - name: cloudbox
        aliases:
          - tautulli
    state: started
