---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: organizr
    state: absent

- name: Create and start container
  docker_container:
    name: organizr
    image: "lsiocommunity/organizr"
    pull: yes
    published_ports:
      - "127.0.0.1:7421:80"
    env:
      PUID: "{{uid.stdout}}"
      PGID: "{{gid.stdout}}"
      VIRTUAL_HOST: "organizr.{{domain}}"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "organizr.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/organizr:/config"
    networks:
      - name: cloudbox
        ipv4_address: 172.18.0.8
        aliases:
          - organizr
    restart_policy: always
    state: started
