---
- name: "Get {{user}} uid"
  shell: "id -u {{user}}"
  register: uid

- name: "Get {{user}} gid"
  shell: "id -g {{user}}"
  register: gid

- name: Stop and remove any existing container
  docker_container:
    name: emby
    state: absent

- name: Check /dev/dri exists
  stat:
    path: "/dev/dri/renderD128"
  register: dev_dri

- name: Create emby directories
  file: "path={{item}} state=directory mode=0775 owner={{user}} group={{user}}"
  with_items:
    - /opt/emby

- name: Create and start container
  docker_container:
    name: emby
    image: "emby/embyserver_netcore:beta"
    pull: yes
    published_ports:
      - "127.0.0.1:8096:8096"
    env:
      UID: "{{uid.stdout}}"
      GID: "{{gid.stdout}}"
      VIRTUAL_HOST: "emby.{{domain}}"
      VIRTUAL_PORT: 8096
      LETSENCRYPT_HOST: "emby.{{domain}}"
      LETSENCRYPT_EMAIL: "{{email}}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/emby:/config"
      - "/mnt/unionfs/Media:/data"
      - "/mnt:/mnt"
    devices: "{{ '/dev/dri/renderD128:/dev/dri/renderD128' if dev_dri.stat.exists == True | default(false) else omit }}"
    networks:
      - name: cloudbox
        aliases:
          - emby
    restart_policy: always
    state: started
